*Numpy*

Python Libraries


In [1]:
import numpy as np

In [2]:
np.__version__

'1.25.2'

In [4]:
a = np.array([2,3,4,5])
b = np.array([[4,5,3,5],[4,6,7,4],[4,1,2,3]])
type(a)

numpy.ndarray

In [5]:
asa = [2, 4, 5, 6]
type(asa)

list

In [6]:
a.ndim  #to check dimensions

1

In [7]:
b.ndim

2

In [8]:
a.shape

(4,)

In [9]:
b.shape

(3, 4)

In [11]:
c = np.ones((3, 4, 2))
c

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [12]:
images = np.ones((16, 16, 3))
images

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
      

In [13]:
images.shape

(16, 16, 3)

In [14]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [15]:
a

array([2, 3, 4, 5])

In [16]:
a2 = np.array([4, 5, 4, 3])
a + a2

array([6, 8, 8, 8])

In [17]:
np.sum(a)

14

In [18]:
a = np.array([4, 5, 6])
b = np.array([5, 4, 3])
a + 5

array([ 9, 10, 11])

In [19]:
np.sum(a*5)

75

In [21]:
np.matmul(b,a)

58

In [22]:
c.mean()

1.0

In [23]:
v = np.array([[1, 2, 3],[4, 5, 6],[4, 3, 2]])
v

array([[1, 2, 3],
       [4, 5, 6],
       [4, 3, 2]])

In [24]:
np.sum(v, axis=0)

array([ 9, 10, 11])

In [25]:
np.sum(v, axis = 1)

array([ 6, 15,  9])

In [26]:
list_a=[[1,2,3],[4,5,6],[7,8,9]]

In [27]:
# list_a[1,1]
list_a[1][1]

5

In [28]:
v

array([[1, 2, 3],
       [4, 5, 6],
       [4, 3, 2]])

In [29]:
a1 = np.array([[1,2],[3, 5]])
a2 = np.array([[4,5],[5,6]])
np.matmul(a1, a2)

array([[14, 17],
       [37, 45]])

In [30]:
a1[0]

array([1, 2])

In [31]:
a1.T[1]

array([2, 5])

In [32]:
ans = np.zeros((2,2))
for i in range(2):
  for j in range(2):
    ans[i,j]=np.sum(a1[i]*a2.T[j])
ans

array([[14., 17.],
       [37., 45.]])

In [33]:
np.matmul(a1,a2)

array([[14, 17],
       [37, 45]])

In [34]:
ans

array([[14., 17.],
       [37., 45.]])

In [35]:
ans.reshape

<function ndarray.reshape>

In [36]:
ans.reshape(1,4)

array([[14., 17., 37., 45.]])

In [37]:
ans.reshape(4,1)

array([[14.],
       [17.],
       [37.],
       [45.]])

In [38]:
def add(a1, a2):
  return a1 + a2

add_num = np.frompyfunc(add,2,1)

add_num([1,2,3],[3,4,5])


array([4, 6, 8], dtype=object)

In [39]:
np.cumsum(a1)

array([ 1,  3,  6, 11])

Numpy From DataCamp Cheatsheet

In [40]:
# Creating Arrays

a = np.array([3, 5, 6, 7])
b = np.array([(2, 4, 5, 6), (6, 7, 8, 4)], dtype = int)
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)

In [41]:
a, b, c

(array([3, 5, 6, 7]),
 array([[2, 4, 5, 6],
        [6, 7, 8, 4]]),
 array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]],
 
        [[3. , 2. , 1. ],
         [4. , 5. , 6. ]]]))

In [42]:
# Initial Placeholders

np.zeros((3, 4))   #create an array of zeros


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.ones((4, 5))   #Create an array of ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
d = np.arange(3, 5, 1)  #Create an array of evenly spaced values


In [45]:
r = np.eye(2)  #Create an identity matrix

In [46]:
# Asking for help

np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [47]:
# Inspecting your array

a.shape  #Array dimensions

(4,)

In [48]:
len(a)   #length of an array

4

In [49]:
b.ndim   #No. of dimensions


2

In [50]:
a.size  #no. of array elements

4

In [51]:
b.dtype.name  #name of data type

'int64'

In [53]:
# Sorting Arrays

a.sort(a)   #Sort an array
c.sort(axis = 0)  #sort the elements of an arrays axis

In [54]:
# Array manipulation

i = np.transpose(a)
i.T

array([3, 5, 6, 7])

In [56]:
# # Adding/ removing Elements

# a.resize((2, 6))   #Return a new array with space (2, 6)

Substting

In [57]:
a[2] #Select the element at the 2nd index

b[1,2] #Select the element at row 1 column 2(equivalent to b[1][2])


8

Slicing

In [58]:
a[0:2]#Select items at index 0 and 1
b[0:2,1] #Select items at rows 0 and 1 in column 1
b[:1]
#Select all items at row0(equivalent to b[0:1, :])
c[1,...] #Same as[1,:,:]
a[ : : -1] #Reversed array a array([3, 2, 1])

array([7, 6, 5, 3])