# Implement Neural Network from Scratch

In [16]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from matplotlib import pyplot as plt
%matplotlib inline

In [17]:
data = pd.read_csv('/content/insurance_data.csv')
data

age  affordibility  bought_insurance
0    22              1                 0
1    25              0                 0
2    47              1                 1
3    52              0                 0
4    46              1                 1
5    56              1                 1
6    55              0                 0
7    60              0                 1
8    62              1                 1
9    61              1                 1
10   18              1                 0
11   28              1                 0
12   27              0                 0
13   29              0                 0
14   49              1                 1
15   55              1                 1
16   25              0                 1
17   58              1                 1
18   19              0                 0
19   18              1                 0
20   21              1                 0
21   26              0                 0
22   40              1                 1
23   45              1                 1
24   50              1                 1
25   54              1                 1
26   23              1                 0
27   46              1                 0

In [18]:
data.shape

(28, 3)

Split train and test set

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data[['age','affordibility']],data.bought_insurance,test_size=0.2, random_state=25)

preprocessing

In [20]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

Model Building

In [21]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])


In [22]:
#model compile

In [23]:
model.compile(optimizer = 'adam',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

In [15]:
model.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
1/1 [==============================] - 0s 49ms/step - loss: 0.5032 - accuracy: 0.9091
Epoch 2/50
1/1 [==============================] - 0s 30ms/step - loss: 0.5032 - accuracy: 0.9091
Epoch 3/50
1/1 [==============================] - 0s 19ms/step - loss: 0.5032 - accuracy: 0.9091
Epoch 4/50
1/1 [==============================] - 0s 26ms/step - loss: 0.5031 - accuracy: 0.9091
Epoch 5/50
1/1 [==============================] - 0s 19ms/step - loss: 0.5031 - accuracy: 0.9091
Epoch 6/50
1/1 [==============================] - 0s 17ms/step - loss: 0.5031 - accuracy: 0.9091
Epoch 7/50
1/1 [==============================] - 0s 16ms/step - loss: 0.5031 - accuracy: 0.9091
Epoch 8/50
1/1 [==============================] - 0s 13ms/step - loss: 0.5030 - accuracy: 0.9091
Epoch 9/50
1/1 [==============================] - 0s 12ms/step - loss: 0.5030 - accuracy: 0.9091
Epoch 10/50
1/1 [==============================] - 0s 14ms/step - loss: 0.5030 - accuracy: 0.9091
Epoch 11/50
1/1 [============

Model Evaluation

In [24]:
model.evaluate(X_test_scaled, y_test)

1/1 [==============================] - 0s 424ms/step - loss: 0.7329 - accuracy: 0.5000


[0.7328789234161377, 0.5]

In [25]:
model.predict(X_test_scaled)

1/1 [==============================] - 0s 138ms/step


array([[0.81305736],
       [0.76494783],
       [0.5646363 ],
       [0.7824498 ],
       [0.8160783 ],
       [0.8334114 ]], dtype=float32)

In [26]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [27]:
# Get the value of weght and bias of the model


In [28]:
coef, intercept = model.get_weights()

In [29]:
coef, intercept

(array([[1.],
        [1.]], dtype=float32),
 array([0.], dtype=float32))

In [30]:
def sigmoid(x):
  import math
  return 1 / (1 + math.exp(-x))
sigmoid(17)

0.9999999586006244

In [31]:
X_test

age  affordibility
2    47              1
10   18              1
21   26              0
11   28              1
14   49              1
9    61              1

In [32]:
def prediction_function(age, affordibility):
    weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)

prediction_function(.47, 1)

<ipython-input-30-91029ae800bc>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.8130573903805676

In [33]:

prediction_function(.18, 1)

<ipython-input-30-91029ae800bc>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.7649478157668872

In [34]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [35]:

def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [36]:
class myNN:
    def __init__(self):
        self.w1 = 1
        self.w2 = 1
        self.bias = 0

    def fit(self, X, y, epochs, loss_thresold):
        self.w1, self.w2, self.bias = self.gradient_descent(X['age'],X['affordibility'],y, epochs, loss_thresold)
        print(f"Final weights and bias: w1: {self.w1}, w2: {self.w2}, bias: {self.bias}")

    def predict(self, X_test):
        weighted_sum = self.w1*X_test['age'] + self.w2*X_test['affordibility'] + self.bias
        return sigmoid_numpy(weighted_sum)

    def gradient_descent(self, age,affordability, y_true, epochs, loss_thresold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)
        for i in range(epochs):
            weighted_sum = w1 * age + w2 * affordability + bias
            y_predicted = sigmoid_numpy(weighted_sum)
            loss = log_loss(y_true, y_predicted)

            w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
            w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))

            bias_d = np.mean(y_predicted-y_true)
            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            bias = bias - rate * bias_d

            if i%50==0:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

            if loss<=loss_thresold:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
                break

        return w1, w2, bias

In [37]:
customModel = myNN()
customModel.fit(X_train_scaled, y_train, epochs=8000, loss_thresold=0.4631)

Epoch:0, w1:0.974907633470177, w2:0.948348125394529, bias:-0.11341867736368583, loss:0.7113403233723417
Epoch:50, w1:1.503319554173139, w2:1.108384790367645, bias:-1.2319047301235464, loss:0.5675865113475955
Epoch:100, w1:2.200713131760032, w2:1.2941584023238903, bias:-1.6607009122062801, loss:0.5390680417774752
Epoch:150, w1:2.8495727769689085, w2:1.3696895491572745, bias:-1.986105845859897, loss:0.5176462164249294
Epoch:200, w1:3.443016970881803, w2:1.4042218624465033, bias:-2.2571369883752723, loss:0.5005011269691375
Epoch:250, w1:3.982450494649576, w2:1.4239127329321233, bias:-2.494377365971801, loss:0.48654089537617085
Epoch:300, w1:4.472179522095915, w2:1.438787986553552, bias:-2.707387811922373, loss:0.4750814640632793
Epoch:350, w1:4.917245868007634, w2:1.4525660781176122, bias:-2.901176333556766, loss:0.46561475306999006
Epoch:366, w1:5.051047623653049, w2:1.4569794548473887, bias:-2.9596534546250037, loss:0.46293944095888917
Final weights and bias: w1: 5.051047623653049, w2: 

In [38]:
coef, intercept

(array([[1.],
        [1.]], dtype=float32),
 array([0.], dtype=float32))

In [39]:
X_test_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [41]:
model.predict(X_test_scaled)

1/1 [==============================] - 0s 30ms/step


array([[0.81305736],
       [0.76494783],
       [0.5646363 ],
       [0.7824498 ],
       [0.8160783 ],
       [0.8334114 ]], dtype=float32)